# This action runs the Selenium automated tests

name: UI Automated Testing
on:
  push:
    branches: [ "Selenium_UI_test" ]
  pull_request:
    branches: [ "Selenium_UI_test" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  build:
    runs-on: windows-latest
    
    env:
      SOURCE_DIR: ${{ github.workspace }}\Selenium_Nunit_UI_Test
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 6.0.x
      
      - name: Install dependencies
        run: dotnet restore ${{ env.SOURCE_DIR }}
        
      - name: Build
        run: dotnet build ${{ env.SOURCE_DIR }} --configuration Release --no-restore
        
      - name: Test
        run: dotnet test ${{ env.SOURCE_DIR }} --no-restore --verbosity normal
